# Generated by Django 3.2.7 on 2021-11-28 22:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(to='images.Location'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
