# Generated by Django 3.2.9 on 2021-11-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
