# Generated by Django 3.2.9 on 2021-11-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(null=True, to='images.Location'),
        ),
    ]
